import Head from 'next/head'
import Layout from '../Components/Layout';

const Home:React.FC = () => {
  return (
    <div>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.omninews.com.br/wp-content/uploads/2019/09/Alecive-Flatwoken-Apps-Amazon.ico" />
      </Head>

      <main>
        <Layout>
          <div>
            <ul>
              <li>
                <a href="">link</a>
              </li>
              <li>
                <a href="">link</a>
              </li>
            </ul>
          </div>
        </Layout>
      </main>
    </div>
  )
}

export default Home;