import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Oman',
            email: 'omanapple42@hotmail.com',
            password: bcrypt.hashSync('oman120600'),
            isAdmin: true,
        },
        {
            name: 'cris',
            email: 'anacristinapessoa4@hotmail.com',
            password: bcrypt.hashSync('cris1430'),
            isAdmin: false,
        }
    ],
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 120,
            brand: 'Adidas',
            rating: 4.9,
            numReviews: 12,
            countInStock: 8,
            description: 'A popular shirt',
        },
        {
            name: 'Classic Shirt',
            slug: 'classic-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 98,
            brand: 'Fila',
            rating: 3.9,
            numReviews: 4,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Premium Pants',
            slug: 'premium-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 765,
            brand: 'gucci',
            rating: 4.9,
            numReviews: 9,
            countInStock: 2,
            description: 'A premium pants',
        },
        {
            name: 'Free Pants',
            slug: 'free-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 250,
            brand: 'Hugo Boss',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Summer Pants',
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 250,
            brand: 'Hugo Boss',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Summer Pants',
        },
        {
            name: 'Black Sheep Pineapple Ice',
            slug: 'black-sheep-pineapple-ice-600-puffs',
            category: 'Pods',
            image: '/images/pods/black_sheep_pineapple_ice.jpg',
            price: 100,
            brand: 'Black Sheep',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Black Sheep Pineeaple Ice 600 puffs',
        },
        {
            name: 'Black Sheep Mango Ice',
            slug: 'black-sheep-mango-ice-600-puffs',
            category: 'Pods',
            image: '/images/pods/black-sheep-mango-ice.jpg',
            price: 100,
            brand: 'Black Sheep',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Black Sheep Mango Ice 600 puffs',
        },
        {
            name: 'Black Sheep Mint Ice',
            slug: 'black-sheep-mint-ice-600-puffs',
            category: 'Pods',
            image: '/images/pods/black-sheep-mint-ice.jpg',
            price: 100,
            brand: 'Black Sheep',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Black Sheep Mint Ice 600 puffs',
        },
        {
            name: 'Black Sheep Grape Ice',
            slug: 'black-sheep-grape-ice-600-puffs',
            category: 'Pods',
            image: '/images/pods/black-sheep-grape-ice.jpg',
            price: 100,
            brand: 'Black Sheep',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Black Sheep Grape Ice 600 puffs',
        },
        {
            name: 'Black Sheep Peach Ice',
            slug: 'black-sheep-Peach-ice-600-puffs',
            category: 'Pods',
            image: '/images/pods/black-sheep-peach-ice.jpg',
            price: 100,
            brand: 'Black Sheep',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Black Sheep Peach Ice 600 puffs',
        },
        {
            name: 'Black Sheep Frosted Barries',
            slug: 'black-sheep-frosted-barries-600-puffs',
            category: 'Pods',
            image: '/images/pods/black-sheep-frosted-ice.jpg',
            price: 100,
            brand: 'Black Sheep',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Black Sheep Frosted Barries 600 puffs',
        },
        {
            name: 'Ignite Razz Ice',
            slug: 'ignite-razz-ice-1500-puffs',
            category: 'Pods',
            image: '/images/pods/ignite-razz-ice-plus.jpg',
            price: 100,
            brand: 'Ignite',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Ignite Razz Ice 1500 puffs',
        },
        {
            name: 'Ignite Strawbarry Guava Ice',
            slug: 'ignite-strawbarry-guava-ice-1500-puffs',
            category: 'Pods',
            image: '/images/pods/ignite-guava-ice-1500.jpg',
            price: 100,
            brand: 'Ignite',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Ignite Strawbarry Ice 1500 puffs',
        },
        {
            name: 'Ignite Blueberry Ice',
            slug: 'ignite-blueberry-ice-1500-puffs',
            category: 'Pods',
            image: '/images/pods/ignite-blueberry-ice.jpg',
            price: 100,
            brand: 'Ignite',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Ignite Blueberry Ice 1500 puffs',
        },
        {
            name: 'Ignite Peach Ice',
            slug: 'ignite-peach-ice-1500-puffs',
            category: 'Pods',
            image: '/images/pods/ignite-peach-ice.jpg',
            price: 100,
            brand: 'Ignite',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Ignite Peach Ice 1500 puffs',
        },
        {
            name: 'Ignite Lychee Ice',
            slug: 'ignite-lychee-ice-1500-puffs',
            category: 'Pods',
            image: '/images/pods/ignite-lychee-ice.jpg',
            price: 100,
            brand: 'Ignite',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Ignite Lychee Ice 1500 puffs',
        },
        {
            name: 'Ignite Cherry Ice',
            slug: 'ignite-cherry-ice-1500-puffs',
            category: 'Pods',
            image: '/images/pods/ignite-cherry-ice-1500.jpg',
            price: 100,
            brand: 'Ignite',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Ignite Cherry Ice 1500 puffs',
        },
        {
            name: 'Ignite Orange Ice',
            slug: 'ignite-orange-ice-1500-puffs',
            category: 'Pods',
            image: '/images/pods/ignite-orange-ice.jpg',
            price: 100,
            brand: 'Ignite',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Ignite Orange Ice 1500 puffs',
        },
    ]
}

export default data;