const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 120,
            brand: 'Adidas',
            rating: 4.9,
            numReviews: 12,
            countInStock: 8,
            description: 'A popular shirt',
        },
        {
            name: 'Classic Shirt',
            slug: 'classic-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 98,
            brand: 'Fila',
            rating: 3.9,
            numReviews: 4,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Premium Pants',
            slug: 'premium-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 765,
            brand: 'gucci',
            rating: 4.9,
            numReviews: 9,
            countInStock: 2,
            description: 'A premium pants',
        },
        {
            name: 'Free Pants',
            slug: 'free-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 250,
            brand: 'Hugo Boss',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Summer Pants',
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 250,
            brand: 'Hugo Boss',
            rating: 4.7,
            numReviews: 13,
            countInStock: 9,
            description: 'Summer Pants',
        },
    ]
}

export default data;